### PR TITLE
new icon: windows11 (original, plain)

### PR DESCRIPTION
**Pull request by Panquesito7**
# **New icon section**

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] The PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date

---
# **New feature section**

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *New Feature: a brief description of feature*

### CODE REVIEW

**Comment by Panquesito7** [comment]
@Thomas-Boi.

**Comment by Thomas-Boi** [comment]
Seems like the issue still persist and the problem is not with Selenium. After doing some research, there was a similar issue before with taking screenshot of canvases in Firefox. However, this apparently has been [fixed](https://github.com/mozilla/geckodriver/issues/1306). 

I'll test your icons locally and try to resolve it. Hopefully, we can get it in for the next release

**Comment by Thomas-Boi** [comment]
Seems like it wasn't as fixed as I thought: https://bugzilla.mozilla.org/show_bug.cgi?id=1471265

**Comment by Thomas-Boi** [comment]
I've narrowed the issue down:
- Seems like Selenium can't take pictures of elements that aren't visible in the page
- However, the element that I selected IS visible. I don't know why it isn't the case here. The only change is a warning about multi-colored font.

I'm investigating this further. Hopefully I'll figure it out by tonight

**Comment by Thomas-Boi** [comment]
So I found the issue:

image

The code was failing here since it can't take pictures of the greyed out element. This is because the element is not visible. This didn't happen when I first developed the script. I'll now check for non-visible elements before taking screenshots.

**Pull request closed without merging**
